# this file loads all the packages and initialises the environment
install.packages("installr") 
library(installr)
updateR()
update.packages(ask=FALSE, checkBuilt=TRUE)
install.packages("sf")
install.packages("ggplot2")
install.packages("manipulate")
install.packages("gganimate")
install.packages("tidyr")
install.packages("mapview")
install.packages("tidyverse")
install.packages("magick")
install.packages("scales")
install.packages("sf")
install.packages("transformr")
install.packages("gifski")
install.packages("mapview")

install.packages("Orcs")
install.packages("purrr")
install.packages("devtools")
install.packages("rmarkdown")
install.packages("raster", dependencies = TRUE)
install.packages("Orcs", dependencies = TRUE)
install.packages("Rtools", dependencies = TRUE)
library(rsconnect)
library(shiny)
library(data.table)
library(magrittr)
library(gifski)
library(mapview)
library(magick)
library(transformr)
library(sf)
library(scales)
library(ggplot2)
library(gganimate)
library(manipulate)
library(dplyr)
library(plyr)
library(rlang)
library(tidyfast)
library(dtplyr)
library(tidyr)
library(tidyverse)
library(raster)
library(Orcs)
library(lubridate)
library(purrr)
library(rmarkdown)
library(mapview)
library(raster)
library(renv)
install.packages('Rcpp', dependencies = TRUE)
install.packages('Rtools')
